### ISSUE TITLE
動かなかったけど、動くようになりました報告

### ISSUE THREAD

**Issue by omega-takai** [kawamataryo/sync-raise-a-hand#2]
### 概要

Chromeウェブストアから拡張機能をインストールして早速Meetで動作確認したところ、動かなかったです。
しかしアクセス許可を弄ってみたところ期待通り動くようになったので報告しておきます。

<br>

### 状況

![image](https://user-images.githubusercontent.com/10617629/133178557-8b33ccaa-db44-4412-a7d4-c162e55eb5da.png)

```
$ sw_vers

ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1323
```

```
$ system_profiler SPHardwareDataType

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro16,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 2.6 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
```

```
$ brew info --cask google-chrome

google-chrome: 93.0.4577.82 (auto_updates)
https://www.google.com/chrome/
/usr/local/Caskroom/google-chrome/87.0.4280.88,4280.88 (61.7KB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/google-chrome.rb
==> Name
Google Chrome
```

<br>

### 動かない → 動くの手順

1. Chromeウェブストアから **Sync Raise hand** をインストール
2. `https://meet.google.com/` をChromeで開く
    3. 新しい会議を作成
    4. Meet会議内で **Sync Raise hand** をToggleSwitch
    5. 手を上げてみる（Meet挙手は動かない）
6. Chromeの設定を開く `chrome://settings/content#media-stream-mic`
7. 権限 ＞ カメラ ＞ `https://meet.google.com:443`
    8. カメラが許可状態であることを確認
    9. JavaScript 項目を変更 `許可（デフォルト）` → `許可`
10. 先程開いていたMeetに戻る
11. 表示されている「再読み込み」を押下
12. Meet会議内で **Sync Raise hand** をToggleSwitch
13. 手を上げてみる（Meet挙手が同期で動いた 🎉 ）

※その後、JavaScript 項目を変更 `許可`  → `許可（デフォルト）` しても期待通りに動きました

**Comment by kawamataryo** [comment]
詳細な報告ありがとうございます！！
とても助かります🙏

記載頂いた内容は、READMEにTroubleshootingとして追加します！！

**Comment by omega-takai** [comment]
ありがとうございます！貢献できて嬉しいです 🙌

**Comment by kawamataryo** [comment]
https://github.com/kawamataryo/sync-raise-hand#-troubleshooting に説明を追記したので、クローズします！
